# Generated by Django 5.0.2 on 2024-02-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='stack_tech',
            field=models.TextField(blank=True, verbose_name='Stack of technologies'),
        ),
        migrations.AlterField(
            model_name='exp',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
